//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spjeff_partners_web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PartnerEntities : DbContext
    {
        public PartnerEntities()
            : base("name=PartnerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<AddressTypes> AddressTypes { get; set; }
        public virtual DbSet<AgreementDocumentMetaData> AgreementDocumentMetaData { get; set; }
        public virtual DbSet<AgreementDocuments> AgreementDocuments { get; set; }
        public virtual DbSet<AgreementDocumentTypes> AgreementDocumentTypes { get; set; }
        public virtual DbSet<Communications> Communications { get; set; }
        public virtual DbSet<DocumentPrivacy> DocumentPrivacy { get; set; }
        public virtual DbSet<ForumComments> ForumComments { get; set; }
        public virtual DbSet<Forums> Forums { get; set; }
        public virtual DbSet<ForumThreads> ForumThreads { get; set; }
        public virtual DbSet<PartnerDocumentMetaData> PartnerDocumentMetaData { get; set; }
        public virtual DbSet<PartnerDocuments> PartnerDocuments { get; set; }
        public virtual DbSet<PartnerDocumentTypes> PartnerDocumentTypes { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<UserParks> UserParks { get; set; }
        public virtual DbSet<UserPartners> UserPartners { get; set; }
        public virtual DbSet<UserRegions> UserRegions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
