//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spjeff_partners_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerDocuments
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public byte[] Data { get; set; }
        public string ContentType { get; set; }
        public long Size { get; set; }
        public string Path { get; set; }
    }
}
