//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spjeff_partners_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        public System.Guid Id { get; set; }
        public System.Guid OwningId { get; set; }
        public Nullable<System.Guid> UnitTypeId { get; set; }
        public string StreetAddress1 { get; set; }
        public string StreetAddress2 { get; set; }
        public string City { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
        public Nullable<System.Guid> StateId { get; set; }
        public Nullable<System.Guid> ZipId { get; set; }
        public string Zip { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
