//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spjeff_partners_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgreementDocumentMetaData
    {
        public System.Guid Id { get; set; }
        public System.Guid OwningId { get; set; }
        public Nullable<System.Guid> UnitTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string AgreementNumber { get; set; }
        public string AgreementTypeText { get; set; }
    }
}
