//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spjeff_partners_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string UserPrincipalName { get; set; }
        public string Phone { get; set; }
        public string StreetAddress { get; set; }
        public Nullable<System.Guid> StateId { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string DisplayName { get; set; }
        public string Name { get; set; }
        public string DistinguishedName { get; set; }
        public string CommonName { get; set; }
        public string ObjectSid { get; set; }
        public string Comments { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsNps { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
