//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spjeff_partners_web
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPartners
    {
        public System.Guid UserId { get; set; }
        public System.Guid PartnerId { get; set; }
    }
}
